package com.example.proiect_dam_retete;

public enum EIngredients {
    EGGS,FLOUR,SUGAR,OIL,SALT,BLACK_PEPPER,
    YEAST,CHEESE,HAM,OLIVES,BACON,TOMATO_SAUCE,
    CHICKEN,MILK,CHOCOLATE,JAM,PASTA,PARMESAN,POTATOES,BLUEBERRIES,
    OAT,CUCUMBERS,CARROTS,ONIONS,PARSLEY,RICE,SALMON,LEMON,TOMATOES,GARLIC,BASIL,
    MUSHROOMS,COOKING_CREAM,HONEY,BREAD,CINNAMON,AVOCADO,TORTILLA,BAKING_POWDER,COCOA,
    MOZZARELLA,BUTTER,BEEF,PORK,BREAM,BELL_PEPPERS,APPLES,SHRIMPS,ZUCCHINI,TURKEY,
    CABBAGE,BISCUITS,CELERY,CREAM_CHEESE,VANILLA_EXTRACT,ALMONDS,BAY_LEAVES,BEANS,BEETS,STRAWBERRIES,
    CAULIFLOWER,SOUR_CREAM,PESTO,COCONUT,YOGURT,LIME,OLIVE_OIL,ROSEMARY,SPINACH,SAUSAGE,SALAD,BREAD_CRUMBS,
    PAPRIKA,PEAS,CORN,KANAFEH,PISTACHIO, TOMATO
}


